#!/usr/bin/env python3
"""Builds the pre-compiled fatbin for the graph_do_while condition kernel.

Requires the CUDA toolkit (nvcc) to be installed.

The output is a C header (graph_do_while_cond_fatbin.h) containing the fatbin
as a byte array, which is compiled into the quadrants binary. At runtime
this lets us load the condition kernel without needing libcudadevrt.a on
the user's system.

Usage:
    python scripts/build_condition_kernel_fatbin.py

See docs/source/user_guide/building_cudagraph_conditional_fatbin.md
"""

import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC = REPO_ROOT / "quadrants" / "runtime" / "cuda" / "graph_do_while_cond.cu"
OUT_HEADER = REPO_ROOT / "quadrants" / "runtime" / "cuda" / "graph_do_while_cond_fatbin.h"

SM_VERSIONS = [90, 100, 120]
SM_TARGETS = [f"-gencode=arch=compute_{v},code=sm_{v}" for v in SM_VERSIONS]


def find_nvcc() -> str:
    nvcc = shutil.which("nvcc")
    if nvcc:
        return nvcc
    candidates = [os.path.join(os.environ[v], "bin", "nvcc") for v in ("CUDA_HOME", "CUDA_PATH") if v in os.environ]
    candidates.append("/usr/local/cuda/bin/nvcc")
    for candidate in candidates:
        if Path(candidate).exists():
            return candidate
    sys.exit("Error: nvcc not found. Install the CUDA toolkit and add it to PATH, or set CUDA_HOME.")


def run(cmd: list[str]) -> None:
    print(f"  {' '.join(cmd)}")
    subprocess.check_call(cmd)


def generate_header(fatbin_path: Path, out_path: Path) -> None:
    fatbin_data = fatbin_path.read_bytes()
    header_lines = [
        "// Auto-generated by scripts/build_condition_kernel_fatbin.py",
        "// Do not edit manually. Regenerate with that script.",
        "//",
        "// Source: quadrants/runtime/cuda/graph_do_while_cond.cu",
        f"// SM targets: {', '.join(f'sm_{v}' for v in SM_VERSIONS)}",
        f"// Size: {len(fatbin_data)} bytes",
        "",
        "#pragma once",
        "",
        "#include <cstddef>",
        "",
        "static const unsigned char kConditionKernelFatbin[] = {",
    ]
    for i in range(0, len(fatbin_data), 12):
        chunk = fatbin_data[i : i + 12]
        header_lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    header_lines.append("};")
    header_lines.append("")
    header_lines.append(f"static const std::size_t kConditionKernelFatbinSize = {len(fatbin_data)};")
    header_lines.append("")
    out_path.write_text("\n".join(header_lines), newline="\n")
    print(f"Wrote {out_path} ({len(fatbin_data)} bytes)")


def main() -> None:
    nvcc = find_nvcc()

    with tempfile.TemporaryDirectory() as tmpdir:
        obj_path = Path(tmpdir) / "condition_kernel.o"
        fatbin_path = Path(tmpdir) / "condition_kernel.fatbin"

        print("Compiling ...")
        run([nvcc, "-dc", "-rdc=true", *SM_TARGETS, str(SRC), "-o", str(obj_path)])

        print("Device-linking with libcudadevrt ...")
        run([nvcc, "-dlink", *SM_TARGETS, str(obj_path), "-lcudadevrt", "-fatbin", "-o", str(fatbin_path)])

        print("Generating C header ...")
        generate_header(fatbin_path, OUT_HEADER)

    print("Done.")


if __name__ == "__main__":
    main()
