name: Build and Test
on:
  push:
    branches:
      - master
      - rc-*

env:
  TI_CI: "1"
  TI_SKIP_VERSION_CHECK: 'ON'
  TI_LITE_TEST: ${{ github.event_name == 'pull_request' && ! contains(github.event.pull_request.labels.*.name, 'full-ci') && ! startsWith(github.base_ref, 'rc-') && '1' || '' }}
  TI_TEST_OFFLINE_CACHE: ${{ github.event.schedule == '0 18 * * *' && '1' || '' }}
  CI_IMAGE_VERSION: '202311231829'
  # TI_USE_GIT_CACHE: ${{ vars.TI_USE_GIT_CACHE }}
  TI_USE_GIT_CACHE: '1'  # variables are also not populated on forked PRs
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  show_environ:
    name: Show Environment Variables
    runs-on: [ubuntu-latest]
    steps:
    - name: Environment Variables
      run: env
    - name: Github Object
      run: |
        cat <<'EOF'
        ${{ toJson(github) }}
        EOF

  # build_and_test_windows:
  #   name: Build and Test Windows
  #   # needs: check_files
  #   strategy:
  #     matrix:
  #       extra_markers:
  #       - sm70
  #       - not sm70
  #   runs-on:
  #   - self-hosted
  #   - cn
  #   - windows
  #   - cuda
  #   - OpenGL
  #   - ${{ matrix.extra_markers == 'sm70' && 'sm70' || 'windows' }}
  #   timeout-minutes: ${{ github.event.schedule != '0 18 * * *' && 90 || 180 }}
  #   env:
  #     PY: "3.9"
  #     TAICHI_CMAKE_ARGS: >-
  #       -DTI_WITH_OPENGL:BOOL=OFF
  #       -DTI_WITH_VULKAN:BOOL=ON
  #       -DTI_WITH_DX11:BOOL=ON
  #       -DTI_WITH_DX12:BOOL=ON
  #       -DTI_BUILD_TESTS:BOOL=ON
  #       -DTI_WITH_BACKTRACE=ON
  #       -DTI_WITH_C_API=ON
  #     TI_WANTED_ARCHS: cpu,cuda,vulkan
  #     TI_SKIP_VERSION_CHECK: ON
  #     TI_DEVICE_MEMORY_GB: '1'
  #     TI_RUN_RELEASE_TESTS: '1'

  #   steps:
  #     - name: Workaround checkout issues
  #       run: |
  #         git config --system core.longpaths true
  #         git submodule foreach 'git rev-parse HEAD > /dev/null 2>&1 || rm -rf $PWD'  # no '|| true' here

  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: '0'
  #         submodules: 'recursive'

  #     - uses: actions/setup-python@v4
  #       with:
  #         python-version: 3.9

  #     - name: Build
  #       shell: cmd
  #       run: |
  #         . .github/workflows/scripts/common-utils.ps1
  #         SetGitCachingProxy
  #         python .\.github\workflows\scripts\build.py

  #     - name: Test
  #       id: test
  #       shell: pwsh
  #       run: |
  #         . .github/workflows/scripts/common-utils.ps1
  #         SetGitCachingProxy
  #         .\.github\workflows\scripts\win_test.ps1 -libsDir "$env:LocalAppData/buildbot"
  #       env:
  #         EXTRA_TEST_MARKERS: ${{ matrix.extra_markers }}

  #     - name: Save wheel if test failed
  #       if: failure() && steps.test.conclusion == 'failure'
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: broken-wheel
  #         path: dist/*
  #         retention-days: 7

  #     - name: Cleanup Git Cache Configs
  #       shell: pwsh
  #       if: always()
  #       run: |
  #         . .github/workflows/scripts/common-utils.ps1
  #         UnsetGitCachingProxy
  #         exit 0

  build_and_test_m1:
    name: Build and Test (Apple M1)
    timeout-minutes: ${{ github.event.schedule != '0 18 * * *' && 60 || 120 }}
    strategy:
      matrix:
        include:
          - os: macos-15
            python: 3.9
    defaults:
      run:
        # https://github.com/actions/runner/issues/805#issuecomment-844426478
        shell: '/usr/bin/arch -arch arm64e /bin/bash --noprofile --norc -eo pipefail {0}'
    runs-on: [macos-15]
    env:
      CXX: clang++
      PY: ${{ matrix.python }}
      TAICHI_CMAKE_ARGS: >-
        -DTI_WITH_OPENGL:BOOL=OFF
        -DTI_WITH_CUDA:BOOL=OFF
        -DTI_WITH_VULKAN:BOOL=ON
        -DTI_BUILD_TESTS:BOOL=ON
        -DTI_WITH_C_API=ON
        -DTI_WITH_STATIC_C_API=ON
      TI_WANTED_ARCHS: 'cpu,metal,vulkan'
      PLATFORM: 'm1'
      TI_RUN_RELEASE_TESTS: '1'
    steps:
      - name: Workaround checkout Needed single revision issue
        run: git submodule foreach 'git rev-parse HEAD > /dev/null 2>&1 || rm -rf $PWD' || true

      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          submodules: 'recursive'

      - name: Build
        run: |
          sw_vers
          clang++ --version
          . .github/workflows/scripts/common-utils.sh
          prepare-build-cache
          brew install molten-vk
          brew install llvm@15
          .github/workflows/scripts/build.py
        env:
          CXX: clang++

      - name: Check C-API Export Symbols
        run: |
          . .github/workflows/scripts/common-utils.sh

          .github/workflows/scripts/aot-demo.sh check-c-api-export-symbols

      - name: Test
        id: test
        run: |
          .github/workflows/scripts/unix_test.sh

      - name: Save wheel if test failed
        if: failure() && steps.test.conclusion == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: broken-wheel
          path: dist/*
          retention-days: 7

      - name: Save Bad Captures
        if: failure() && steps.test.conclusion == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: bad-captures
          path: taichi-release-tests/bad-compare/*
          retention-days: 7
